server:
  port: 8086
  context-path: /ui
  session:
    cookie:
      name: UISESSION


security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8087/auth/oauth/token
      userAuthorizationUri: http://localhost:8087/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8087/auth/rest/home/principal


spring:
  thymeleaf:
    cache: false